export const RAY_Solend_ATA = new PublicKey("CGYRG9HJ1oKXEBcaf8hBp3cvCpuAXqr3azcT3mKyUVzQ")
export const WSOL_Solend_ATA = new PublicKey("4nU1ycCrpQFGUVNUkPNH5uBrnYbkevBbF4bevYztZaSy")
export const MSOL_Solend_ATA = new PublicKey("HtY2TXZtXYVATnrKSU2XTVGxHPKZTwc6pS5PqbMd2nzT")
export const SRM_Solend_ATA = new PublicKey("GvANkMuafhMD2h6HsiEdF96XNyf8YKMHy4a9GbUTJE71")
export const SCNSOL_Solend_ATA = new PublicKey("57DLxxcFR1a2m7QaqgF7ARdh3j71SimzUVZGGkUR75uJ")
export const STSOL_Solend_ATA = new PublicKey("7joyah4n3P5tn2psL1XveGhJWPjdbPvWyM9QmKDVcWic")
